[[works]]
name = "knoQ"
tags = ["a", "b"]
screenshot = "knoq.png"
description = """
"""
[[works.links]]
github = "https://github.com/traPtitech/knoQ"
blog = "https://trap.jp/post/1066/"

[[works]]
name = "fooder"
tags = ["a", "b"]
screenshot = "fooder.png"
description = """
"""
[[works.links]]
github = "https://github.com"
blog = "https://trap.jp/post/"
